import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary-fixed": "#bcece3",
        "on-primary": "#ffffff",
        "on-primary-fixed": "#00201c",
        "on-tertiary-fixed-variant": "#574500",
        "error-container": "#ffdad6",
        "surface-container-low": "#f2f4f6",
        "on-secondary-fixed": "#3e0500",
        "on-surface-variant": "#404846",
        "secondary": "#ac331c",
        "surface-dim": "#d8dadc",
        "inverse-on-surface": "#eff1f3",
        "on-tertiary": "#ffffff",
        "secondary-fixed": "#ffdad3",
        "on-primary-fixed-variant": "#204e47",
        "on-secondary-fixed-variant": "#8b1a05",
        "outline": "#707976",
        "on-primary-container": "#a0cfc6",
        "on-secondary": "#ffffff",
        "secondary-container": "#fe6e51",
        "on-background": "#191c1e",
        "surface-container": "#eceef0",
        "on-secondary-container": "#690d00",
        "tertiary-container": "#cca830",
        "surface-container-lowest": "#ffffff",
        "inverse-surface": "#2d3133",
        "tertiary": "#735c00",
        "secondary-fixed-dim": "#ffb4a5",
        "tertiary-fixed-dim": "#e9c349",
        "surface": "#f7f9fb",
        "error": "#ba1a1a",
        "primary-container": "#2d5a53",
        "outline-variant": "#c0c8c5",
        "tertiary-fixed": "#ffe088",
        "on-error-container": "#93000a",
        "on-tertiary-fixed": "#241a00",
        "surface-bright": "#f7f9fb",
        "surface-variant": "#e0e3e5",
        "surface-tint": "#39665f",
        "on-tertiary-container": "#4f3e00",
        "primary": "#13423c",
        "surface-container-highest": "#e0e3e5",
        "on-surface": "#191c1e",
        "inverse-primary": "#a1d0c7",
        "on-error": "#ffffff",
        "primary-fixed-dim": "#a1d0c7",
        "surface-container-high": "#e6e8ea",
        "background": "#f7f9fb"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "gutter": "24px",
        "sidebar-width": "260px",
        "margin-page": "32px",
        "card-padding": "24px",
        "unit": "4px",
        "stack-sm": "8px",
        "stack-md": "16px",
        "stack-lg": "32px",
        "container-padding": "24px"
      },
      fontFamily: {
        "body-lg": ["var(--font-inter)", "sans-serif"],
        "headline-md": ["var(--font-inter)", "sans-serif"],
        "headline-lg": ["var(--font-inter)", "sans-serif"],
        "headline-sm": ["var(--font-inter)", "sans-serif"],
        "stat-lg": ["var(--font-inter)", "sans-serif"],
        "body-md": ["var(--font-inter)", "sans-serif"],
        "label-md": ["var(--font-inter)", "sans-serif"],
        "label-sm": ["var(--font-inter)", "sans-serif"],
        "display-lg": ["var(--font-inter)", "sans-serif"],
        "headline-lg-mobile": ["var(--font-inter)", "sans-serif"]
      },
      fontSize: {
        "body-lg": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
        "headline-md": ["24px", {"lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "600"}],
        "headline-lg": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "headline-sm": ["20px", {"lineHeight": "28px", "fontWeight": "600"}],
        "stat-lg": ["28px", {"lineHeight": "36px", "fontWeight": "700"}],
        "body-md": ["14px", {"lineHeight": "20px", "fontWeight": "400"}],
        "label-md": ["14px", {"lineHeight": "20px", "fontWeight": "500"}],
        "label-sm": ["12px", {"lineHeight": "16px", "fontWeight": "500"}],
        "display-lg": ["48px", {"lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "headline-lg-mobile": ["24px", {"lineHeight": "32px", "fontWeight": "700"}]
      }
    },
  },
  plugins: [],
};
export default config;
